steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      git fetch --depth=2 origin main
      git  log
      git --no-pager diff --name-only HEAD^ HEAD | grep "/" | sed 's%/[^/]*$%%' | sort | uniq > /workspace/diff.txt
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      config=""
      while read line
      do
        echo $line
        image_name="${line}-image"
        if [[ $line == *"notebooks"* ]]; then
          cp -R reports/. $line
          config="${line}/notebookbuild.yaml"
          image_name=${line#"notebooks/"}
          image_name="${image_name}-notebook-image"
          echo "---"
          echo $image_name
          echo "---"
        elif [[ $line == *"reports"* ]]; then
          find notebooks -maxdepth 1 -mindepth 1 -type d > subdirs.txt
          echo "..."
          cat subdirs.txt
          echo "..."
          while read subdir
          do
              cp -R reports/. $subdir
              config="${subdir}/notebookbuild.yaml"
              echo $config
              image_name=${subdir#"notebooks/"}
              image_name="${image_name}-notebook-image"
              echo "~~~"
              echo $image_name
              echo "~~~"
              gcloud builds submit $subdir --config=${config} --substitutions _SHORT_SHA=$SHORT_SHA,_LOCATION=$_LOCATION,_IMAGE=$image_name,_REGISTRY_REPO=$_REGISTRY_REPO,_TAG=$_TAG
          done < subdirs.txt
          continue
        else
          config="${line}/cloudbuild.yaml"
        fi
        echo $config
        if [[ ! -f "${config}" ]]; then
          echo "no such file"
          continue
        fi
        gcloud builds submit $line --config=${config} --substitutions _SHORT_SHA=$SHORT_SHA,_LOCATION=$_LOCATION,_IMAGE=$image_name,_REGISTRY_REPO=$_REGISTRY_REPO,_TAG=$_TAG

      done < /workspace/diff.txt
options:
 logging: CLOUD_LOGGING_ONLY
