steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-t", "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_REPO}/reindex-db-job-image:${_SHORT_SHA}", "-t", "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_REPO}/reindex-db-job-image:${_TAG}", "."]
images: ["${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_REPO}/reindex-db-job-image:${_TAG}"]
