name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      gcp_job:
        required: true
        type: choice
        description: 'Directory of the job to (re-)deploy'
        options:
        - notify-api-day-job
        - reindex-db-job
        - build-triggers
        - reports
      gcp_env:
        description: 'Namespace suffix: one of dev/test/prod'
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

permissions:
  contents: read

jobs:
  run-terraform-apply:
    uses: bcgov/bcregistry-gcp-jobs/.github/workflows/terraform-common-gcs.yml@main
    with:
      gcp_job: ${{ github.event.inputs.gcp_job }}
      gcp_env: ${{ github.event.inputs.gcp_env }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
